def make_event_data(event_stats):
    return {
        'home_corner_kicks': event_stats.get('Corner Kicks', [None, None])[0],
        'home_yellow_cards': event_stats.get('Yellow Cards', [None, None])[0],
        'home_shots': event_stats.get('Shots', [None, None])[0],
        'home_shots_og': event_stats.get('Shots On Goal', [None, None])[0],
        'home_attack': event_stats.get('Attack', [None, None])[0],
        'home_danger_attack': event_stats.get('Dangerous attack', [None, None])[0],
        'home_off_target': event_stats.get('Off Target', [None, None])[0],
        'home_blocked': event_stats.get('Blocked', [None, None])[0],
        'home_free_kicks': event_stats.get('Free Kicks', [None, None])[0],
        'home_possesion': event_stats.get('Possession', [None, None])[0],
        'home_half_possesion': event_stats.get('Possession(HT)', [None, None])[0],
        'home_pass': event_stats.get('Pass', [None, None])[0],
        'home_pass_success': event_stats.get('Pass Success', [None, None])[0],
        'home_fouls': event_stats.get('Fouls', [None, None])[0],
        'home_offsides': event_stats.get('Offsides', [None, None])[0],
        'home_heads': event_stats.get('Heads', [None, None])[0],
        'home_head_success': event_stats.get('Head Success', [None, None])[0],
        'home_saves': event_stats.get('Saves', [None, None])[0],
        'home_tackles': event_stats.get('Tackles', [None, None])[0],
        'home_tackle_success': event_stats.get('Tackle Success', [None, None])[0],
        'home_dribbles': event_stats.get('Dribbles', [None, None])[0],
        'home_throw_ins': event_stats.get('Throw ins', [None, None])[0],
        'home_intercept': event_stats.get('Intercept', [None, None])[0],
        'home_red_cards': event_stats.get('Red Cards', [None, None])[0],
        'away_corner_kicks': event_stats.get('Corner Kicks', [None, None])[1],
        'away_yellow_cards': event_stats.get('Yellow Cards', [None, None])[1],
        'away_shots': event_stats.get('Shots', [None, None])[1],
        'away_shots_og': event_stats.get('Shots On Goal', [None, None])[1],
        'away_attack': event_stats.get('Attack', [None, None])[1],
        'away_danger_attack': event_stats.get('Dangerous attack', [None, None])[1],
        'away_off_target': event_stats.get('Off Target', [None, None])[1],
        'away_blocked': event_stats.get('Blocked', [None, None])[1],
        'away_free_kicks': event_stats.get('Free Kicks', [None, None])[1],
        'away_possesion': event_stats.get('Possession', [None, None])[1],
        'away_half_possesion': event_stats.get('Possession(HT)', [None, None])[1],
        'away_pass': event_stats.get('Pass', [None, None])[1],
        'away_pass_success': event_stats.get('Pass Success', [None, None])[1],
        'away_fouls': event_stats.get('Fouls', [None, None])[1],
        'away_offsides': event_stats.get('Offsides', [None, None])[1],
        'away_heads': event_stats.get('Heads', [None, None])[1],
        'away_head_success': event_stats.get('Head Success', [None, None])[1],
        'away_saves': event_stats.get('Saves', [None, None])[1],
        'away_tackles': event_stats.get('Tackles', [None, None])[1],
        'away_tackle_success': event_stats.get('Tackle Success', [None, None])[1],
        'away_dribbles': event_stats.get('Dribbles', [None, None])[1],
        'away_throw_ins': event_stats.get('Throw ins', [None, None])[1],
        'away_intercept': event_stats.get('Intercept', [None, None])[1],
        'away_red_cards': event_stats.get('Red Cards', [None, None])[1]
    }